---
# tasks file for harden-linux

- name: Include initial assessment tasks
  import_tasks: initial_assessment.yml
  when: include_initial_assessment | default(false)

# Set timezone (conditionally included)
- name: Include timezone tasks
  import_tasks: base.yml
  when: import_timezone | default(false)
    
# Tasks for User and Access Management (conditionally included)
- name: Include user access management tasks
  import_tasks: user_access_management.yml
  when: import_user_access_management | default(false)

# Tasks for Password Policies (conditionally included)

# Tasks for Password Policies
- name: Include password_policies tasks
  import_tasks: password_policies.yml
  when: import_password_policies | default(false)

- name: Include service management tasks
  import_tasks: service_management.yml
  when: include_service_management | default(false)

- name: Include network security tasks
  import_tasks: network_security.yml
  when: include_network_security | default(false)

- name: Include service management tasks
  import_tasks: service_management.yml
  when: include_service_management | default(false)  

- name: Include network security tasks
  import_tasks: network_security.yml
  when: include_network_security | default(false) 

- name: Include file permissions tasks
  import_tasks: file_permissions.yml
  when: include_file_permissions | default(false)
#>>>>>>> backup-branch

- name: Include system auditing tasks
  import_tasks: system_auditing.yml
  when: include_system_auditing | default(false)

- name: Include kernel os hardening  tasks
  import_tasks: kernel_os_hardening.yml 
  when: include_kernel_os_hardening | default(false)


- name: Include advanced security  tasks
  import_tasks: advanced_security.yml
  when: include_advanced_security | default(false)

- name: Include compliance  tasks
  import_tasks: compliance.yml
  when: include_compliance | default(false)

- name: Include automatedupdates tasks
  import_tasks: automated_updates.yml
  when: include_automated_updates | default(false)

