- name: Enforce minimum password length in PAM
  lineinfile:
    path: "{{ pam_password_conf_path }}"
    regexp: '^password requisite pam_pwquality.so'
    line: 'password requisite pam_pwquality.so minlen={{ min_password_length }}'

- name: Enforce max repeat characters in PAM
  lineinfile:
    path: "{{ pam_password_conf_path }}"
    regexp: '^password requisite pam_pwquality.so'
    line: 'password requisite pam_pwquality.so minlen={{ min_password_length }} maxrepeat={{ max_repeat_characters }}'
