# Set up basic system logging using variables
- name: Enable and configure basic system logging
  lineinfile:
    path: "{{ rsyslog_config_path }}"
    regexp: "{{ rsyslog_authpriv_regex }}"
    line: "authpriv.* {{ secure_log_file }}"
    
# Install basic audit tool using variable for package name
- name: Install auditd package
  apt:
    name: "{{ auditd_package }}"
    state: present
