---
# vars file for harden-linux
timezone: "America/Toronto"  # Change this to your desired timezone

# Variables for User and Access Management
ssh_config_path: "/etc/ssh/sshd_config"
permit_root_login: "no"

# Variables for Password Policies
pam_password_conf_path: "/etc/pam.d/common-password"
min_password_length: 12
max_repeat_characters: 3  # Maximum number of repeated characters allowed in passwords

# Variables for Service Management
unnecessary_services:
  - name: telnet
  - name: ftp


# Vars for network security
firewall_rules:
  # Allow SSH access on port 22 using the TCP protocol
  - rule: allow
    port: '22'
    proto: tcp
    state: enabled  

  # Example: Allow HTTP traffic on port 80 (if needed)
  # Uncomment the following lines if you want to allow HTTP
  - rule: allow
    port: '80'
    proto: tcp
    state: enabled

  # Example: Allow HTTPS traffic on port 443 (if needed)
  # Uncomment the following lines if you want to allow HTTPS
  - rule: allow
    port: '443'
    proto: tcp
    state: enabled


  # Deny all other incoming traffic (for both TCP and UDP)
  - rule: deny
    port: '1:65535'
    proto: tcp
    state: enabled

  - rule: deny
    port: '1:65535'
    proto: udp
    state: enabled
#=======
# vars file for network security

firewall_rules:
  - rule: allow
    port: 22
    proto: tcp
  - rule: deny

sshd_config_path: /etc/ssh/sshd_config

# Variables for permissions
file_permissions:
  - { path: '/etc/ssh', mode: '0700' }  # Example: SSH directory
  - { path: '/var/log', mode: '0750' }  # Example: Logs directory
  - { path: '/etc/passwd', mode: '0644' }  # Example: System file

directory_permissions:  # Ensure this variable is defined
  - { path: '/etc', mode: '0755' }
  - { path: '/var', mode: '0755' }

umask_value: '027'

# Directory and mode for private key files
private_key_path: "/etc"
private_key_mode: '0600'

# Ownership for sensitive directories
sensitive_directories:
  - { path: '/etc', owner: 'root', group: 'root' }
  - { path: '/var', owner: 'root', group: 'root' }

# Path for umask configuration
profile_path: "/etc/profile"
  

auditd_package: auditd
rsyslog_config_path: /etc/rsyslog.conf
secure_log_file: /var/log/secure
rsyslog_authpriv_regex: '^authpriv.*'


# Variables for Kernel and OS-Level Hardening
# --------------------------------------------
kernel_parameters:
  - { name: 'net.ipv4.ip_forward', value: '0' }
  - { name: 'net.ipv6.conf.all.disable_ipv6', value: '1' }
#---------------------------------------------

# Package for kernel management
# --------------------------------------------
kernel_package: linux-image-generic
#---------------------------------------------  

# Variables for Advanced Security Configurations
# ---------------------------------------------
#selinux_state: "enforcing"  # State of SELinux
selinux_state: "permissive"  # allowing you to see how it might affect your system without breaking anything  
fail2ban_enabled: true       # Enable or disable Fail2Ban
fail2ban_package: "fail2ban"  # Package name for Fail2Ban
fail2ban_config_template: "fail2ban.j2"  # Jinja2 template for Fail2Ban configuration
fail2ban_config_dest: "/etc/fail2ban/jail.local"  # Destination for the Fail2Ban configuration
#-------------------------------------------------------
  
# Variables for complaince
# -------------------------------------------------------
reboot_message: "Rebooting after applying CSI compliance"
reboot_timeout: 300

# List of critical services to check
critical_services:
  - ssh
  - apache2
  - mysql  
#-------------------------------------------------------   
