---
dependency:
  name: galaxy
  options:
    requirements-file: ../../requirements.yml
driver:
  name: docker
platforms:
  - name: ubuntu-2204
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    privileged: true
    command: /lib/systemd/systemd
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
  inventory:
    host_vars:
      ubuntu-2204:
        hardening_audit_mode: false
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - create
    - converge
    - idempotence
    - verify
    - destroy
