---
# handlers file for harden-linux

# Handlers for User and Access Management

- name: Restart SSH
  service:
    name: ssh
    state: restarted

# Advanced security
- name: Restart fail2ban
  service:
    name: fail2ban
    state: restarted

