---
- name: Basic System Hardening
  hosts: all
  become: yes
  roles:
    - role: harden-linux
      vars:
        import_timezone: true  # To include the timezone task
        timezone: "UTC"  # Set the desired timezone
        include_automated_updates: false
        include_compliance: false
        include_advanced_security: false
        include_kernel_os_hardening: false
        include_system_auditing: false
        include_file_permission: false
        include_network_security: false
        include_service_management: false
        import_timezone: false
        import_user_access_management: false
        import_password_policies: false  
