---
- name: Network Security
  hosts: all
  become: yes
  roles:
    - role: harden-linux
      tags: network_security
  vars:
    include_file_permission: true
    include_network_security: false
    include_service_management: false
    import_timezone: false
    import_user_access_management: false
    import_password_policies: false

