---
- name: kernel_os_hardening
  hosts: all
  become: yes
  roles:
    - role: harden-linux
  vars:
    include_kernel_os_hardening: true
    include_system_auditing: false
    include_file_permission: false
    include_network_security: false
    include_service_management: false
    import_timezone: false
    import_user_access_management: false
    import_password_policies: false

