---
- name: Network Security
  hosts: all
  become: yes
  roles:
    - role: harden-linux
      tags: network_security
  vars:
    include_network_security: true  # Ensure that the network security tasks are included
    include_service_management: false
    import_timezone: false  
    import_user_access_management: false
<<<<<<< HEAD
    import_password_policies: false    


=======
    import_password_policies: false 
>>>>>>> backup-branch
