---
- name: Service Management
  hosts: all
  become: yes
<<<<<<< HEAD

  roles:
    - role: harden-linux
      vars:
        include_service_management: true  # Ensures only service management tasks run
        import_timezone: false            # Skips timezone tasks
        import_user_access_management: false  # Skips user and access management tasks
        import_password_policies: false    # Skips password policy tasks
        include_network_security: false    # Skips network security tasks
=======
  roles:
    - harden-linux
>>>>>>> backup-branch

