---
- name: User and Access Management
  hosts: all
  become: yes

  roles:
<<<<<<< HEAD
    - role: harden-linux
      vars:
        import_user_access_management: true  # user and access management tasks run
        import_timezone: false               # Skips timezone tasks
        import_password_policies: false      # Skips password policy tasks
        include_service_management: false    # Skips service management tasks
        include_network_security: false      # Skips network security tasks
=======
    - harden-linux  
>>>>>>> backup-branch

